### ISSUE TITLE
Optionable stuff

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/HashPokemonGo#15]
I will highlight a few things which should be changeable via config files or inizialization values (in the `some.value || defaultValue` fashion):
- Port number https://github.com/PokemonGoers/HashPokemonGo/blob/develop/sentiment_feed/sentimentFeed.js#L1
- Port number https://github.com/PokemonGoers/HashPokemonGo/blob/develop/mobDetection/mobdetect.js#L5
- https://github.com/PokemonGoers/HashPokemonGo/blob/develop/mobDetection/mobdetect.js#L11 AND https://github.com/PokemonGoers/HashPokemonGo/blob/develop/mobDetection/mobdetect.js#L14 AND https://github.com/PokemonGoers/HashPokemonGo/blob/develop/mobDetection/mobdetect.js#L17

I'm pretty sure you just have this just for testing purposes and that the idea is that at the end you export the `mobDetection` and `sentimentFeed` as functions (the latter accepting as options the elements to listen to) of your npm packages, but just to confirm: https://github.com/PokemonGoers/HashPokemonGo/blob/develop/main.js#L21 this also should be configurable

**Comment by phdowling** [comment]
The main.js file serves as our own demo, mainly. We will export whatever is part of the hashpokemongo module!

**Comment by phdowling** [comment]
I've addressed your issue in this commit: https://github.com/PokemonGoers/HashPokemonGo/commit/c339a9fae57976608bb1e1fcf519e9bd712544fb

It's now such that we export one function per module, which takes some options object as an argument, and returns our "actual" module exports. From [here](https://github.com/PokemonGoers/HashPokemonGo/blob/develop/main.js#L35) on you can see the new usage.

Does this resolve this issue?

**Comment by sacdallago** [comment]
Yes. We can come back here should issues come up when importing the stuff with project A
