### ISSUE TITLE
Accessing tweet texts

### ISSUE THREAD

**Issue by mfkaptan** [PokemonGoers/HashPokemonGo#19]
Hey guys,

Catch-Em-All here. We need to access the tweet texts. I read your issue history and saw that you don't have a public rest api for that. My question is do you store the tweet texts and how could we acces them?

Thanks
@mfkaptan

**Comment by sockeqwe** [comment]
No, we don't store the text of the tweets because we only have to store the sentiment score.
However, the live tweet sentiment analysis API  (via websockets) also includes the text of the tweet, if that helps.

Otherwise, maybe @PokemonGoers/pokedata  is storing tweets with text.

**Comment by mfkaptan** [comment]
Thanks for the answer @sockeqwe . Actually pokedata team redirected me to your team because they said they are not storing the tweet texts.

**Comment by sockeqwe** [comment]
Where do you want to display the tweet's text?

**Comment by mfkaptan** [comment]
In the pokedex-detail page we wanted to show the related tweets for each pokemon.
