### ISSUE TITLE
Project 3: Database for storing Sentiment values

### ISSUE THREAD

**Issue by sockeqwe** [PokemonGoers/HashPokemonGo#6]
Just store the sentiment value like count of positive and negative tweets for a certain time point (every time the twitter miner runs #5 )

From project description:

> Tips: Since you will become the twitter experts, you will join forces with project A (Poke Data) to realize the live-tweet miner.

To be verified. Maybe we don't need that at all or can be shared with project A:

https://github.com/PokemonGoers/PokeData/blob/develop/app/models/pokemonAppearances.js
https://github.com/PokemonGoers/PokeData/blob/develop/app/models/pokemonSighting.js

**Comment by sacdallago** [comment]
From previous experience, it is better if you work directly with project A on this! You have write access on their repo :)
